[book]
authors = ["Andrei Solodovnikov, Mikhail Popov"]
language = "en"
src = "./"
title = "Architectures of Processor Systems"

[output.html]
git-repository-url = "https://github.com/MPSU/APS"
git-repository-icon = "fa-github"
site-url = "/APS/en/"
additional-js  = ["theme/language-switcher.js"]
additional-css = ["theme/language-switcher.css"]
